### ISSUE TITLE
Local LLM option generates content repeatedly

### ISSUE THREAD

**Issue by StargazerEcho** [rashadphz/farfalle#15]
Current main, when used with a local LLM, keeps generating the results content over and over again. Doesn't happen when using Groq,

**Comment by arsaboo** [comment]
This is largely dependent on the model you are running. Try a different model and see if you see the same results.

**Comment by yhyu13** [comment]
@StargazerEcho 
Can confirm that this model dolphin 2.9.1 Yi-1.5 34B 8bit (https://huggingface.co/crusoeai/dolphin-2.9.1-yi-1.5-34b-GGUF/tree/main) can generate gpt4 level of quality locally, with llamacpp openai local server

**Comment by yhyu13** [comment]
@ALL 

Solved guys! It has to do with llm inference server and your model. 

I have succeeded with this backend server and its coresponding models fine tuned for function calling https://github.com/MeetKai/functionary

Here is local script
```
#!/bin/bash

eval "$(conda shell.bash hook)"
conda activate functionary

#NAME=functionary-medium-v2.4-AWQ
NAME=functionary-small-v2.5
TL_PL=1

model_path=meetkai/$NAME
model_names="gpt-4o" 

CUDA_VISIBLE_DEVICES=0 python3 server_vllm.py --model $model_path --host 127.0.0.1 --port 5051 --max-model-len 8192 --served-model-name $model_names --tensor-parallel-size $TL_PL
```
