### ISSUE TITLE
Shows Rate limit exceeded 

### ISSUE THREAD

**Issue by taqihaider7** [rashadphz/farfalle#17]
I am trying to querying the search app but shows rate limit exceeded.
Did you guys add some kind of rate limit for first user? 

![image](https://github.com/rashadphz/farfalle/assets/96980772/3fc489b6-10c1-4f62-acb0-b4215e9be7bd)

**Comment by rashadphz** [comment]
Hey, this should be fixed now. We do have a rate limit but there was a bug with it getting triggered too early. Feel free to reopen this issue if you're still having problems.

**Comment by arsaboo** [comment]
@rashadphz, why do we need a rate limit? for Tavily?

**Comment by rashadphz** [comment]
The rate limit is off by default. It's only applied to the live demo site to avoid misuse.
