### ISSUE TITLE
500: 500: There was an error while searching. 

### ISSUE THREAD

**Issue by Manu-Devloo** [rashadphz/farfalle#30]
when i try searching with searxng i get 

![image](https://github.com/rashadphz/farfalle/assets/95429732/2d9f6e12-ac78-4b42-a6ab-26784d66a065)

.env
SEARCH_PROVIDER=searxng

compose file:
 GNU nano 7.2                                                                                                                       docker-compose.dev.yaml                                                                                                                                 
services:
  backend:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ENABLE_LOCAL_MODELS=${ENABLE_LOCAL_MODELS:-True}
      - SEARCH_PROVIDER=${SEARCH_PROVIDER:-tavily}
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-http://host.docker.internal:8080}
      - REDIS_URL=${REDIS_URL}
    develop:
      watch:
        - action: sync
          path: ./src/backend
          target: /workspace/src/backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NEXT_PUBLIC_LOCAL_MODE_ENABLED=${NEXT_PUBLIC_LOCAL_MODE_ENABLED:-true}
    ports:
      - "3100:3000"
    develop:
      watch:
        - action: sync
          path: ./src/frontend
          target: /app
          ignore:
            - node_modules/

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_BASE_URL:-localhost}/

networks:
  searxng:

**Comment by Red5d** [comment]
I had this error too and fixed it by removing the separate searxng network so that searxng is on the same network with backend and frontend services, and then I set my SEARXNG_BASE_URL=http://searxng:8080 and also added a Redis server (not sure if that's required or not).

**Comment by Manu-Devloo** [comment]
thanks, that worked for me. I did not need a redis database.

**Comment by ramanveerji** [comment]
> when i try searching with searxng i get
> 
> ![image](https://private-user-images.githubusercontent.com/95429732/334852467-2d9f6e12-ac78-4b42-a6ab-26784d66a065.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Njk5MzUsIm5iZiI6MTcyMzQ2OTYzNSwicGF0aCI6Ii85NTQyOTczMi8zMzQ4NTI0NjctMmQ5ZjZlMTItYWM3OC00YjQyLWE2YWItMjY3ODRkNjZhMDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDEzMzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzM2MyYzFhODcyNGE0MDg5YzcwOTc4ZTY4NGYzNGNhZGNkZTgzZmM1MGNkNjIwOGNkNzc4NzQ3YTRlM2MxYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RuFf6qHt4qULiAG949NSkGUvx6BKNwNu3DLw8BO-v4)
> 
> .env SEARCH_PROVIDER=searxng
> 
> compose file: GNU nano 7.2 docker-compose.dev.yaml services: backend: build: context: . dockerfile: ./src/backend/Dockerfile restart: always ports: - "8000:8000" environment: - OLLAMA_HOST=${OLLAMA_HOST:-[http://host.docker.internal:11434}](http://host.docker.internal:11434%7D) - TAVILY_API_KEY=${TAVILY_API_KEY} - OPENAI_API_KEY=${OPENAI_API_KEY} - GROQ_API_KEY=${GROQ_API_KEY} - ENABLE_LOCAL_MODELS=${ENABLE_LOCAL_MODELS:-True} - SEARCH_PROVIDER=${SEARCH_PROVIDER:-tavily} - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-[http://host.docker.internal:8080}](http://host.docker.internal:8080%7D) - REDIS_URL=${REDIS_URL} develop: watch: - action: sync path: ./src/backend target: /workspace/src/backend extra_hosts: - "host.docker.internal:host-gateway" frontend: depends_on: - backend build: context: . dockerfile: ./src/frontend/Dockerfile restart: always environment: - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-[http://localhost:8000}](http://localhost:8000%7D) - NEXT_PUBLIC_LOCAL_MODE_ENABLED=${NEXT_PUBLIC_LOCAL_MODE_ENABLED:-true} ports: - "3100:3000" develop: watch: - action: sync path: ./src/frontend target: /app ignore: - node_modules/
> 
> searxng: container_name: searxng image: docker.io/searxng/searxng:latest restart: unless-stopped networks: - searxng ports: - "127.0.0.1:8080:8080" volumes: - ./searxng:/etc/searxng:rw environment: - SEARXNG_BASE_URL=https://${SEARXNG_BASE_URL:-localhost}/
> 
> networks: searxng:

I deployed backend on render, I am facing same issue, how can I fix it?
I have added tavily and groq api keys there.
