### ISSUE TITLE
fastapi.exceptions.HTTPException: 500: Request timed out.

### ISSUE THREAD

**Issue by llmadd** [rashadphz/farfalle#36]
I have deployed the backend and frontend locally, but I'm encountering an issue where after a single API call, the connection doesn't terminate, and after a while, it outputs a timeout error. Could you please explain what might be causing this?
![721717147405_ pic_hd](https://github.com/rashadphz/farfalle/assets/38323944/2be50d6d-da31-4b08-8bde-21da6df5c18f)
for a while
![711717147384_ pic](https://github.com/rashadphz/farfalle/assets/38323944/5a20eef7-2e6d-4567-8702-3de81fe70d95)

**Comment by rashadphz** [comment]
Hey, sorry for the late response! There have been many updates/bugfixes since then, so hopefully this should no longer be a problem if you follow the new instructions in the README. Let me know if you have any issues!
