### ISSUE TITLE
docker frontend compose error 

### ISSUE THREAD

**Issue by StargazerEcho** [rashadphz/farfalle#4]
After the latest update, I get an error when running docker-compose. I tried clearing my Docker cache. Compose runs as expected up until:

 => ERROR [frontend 4/8] COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./                                                        0.0s
------
 > [frontend 4/8] COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref cc45bce7-4bd0-4851-a627-fba2df5403da::i83e7cgdwq8q8juezfvjt3zxs: "/package.json": not found

**Comment by rashadphz** [comment]
Sorry about that, just pushed a fix. Let me know if it works now.

**Comment by rashadphz** [comment]
I'm closing this out, feel free to re-open if you're still having issues!
