### ISSUE TITLE
Unsupported config option for services.backend : 'develop'

### ISSUE THREAD

**Issue by Dragonflysg** [rashadphz/farfalle#40]
when i run the docker-compose -f docker-compose.dev.yaml up -d. i get an error that says "

`ERROR: The Compose file './docker-compose.dev.yaml' is invalid because:`
`Unsupported config option for services.backend: 'develop'`
`Unsupported config option for services.frontend: 'develop'`

My docker compose version is : 

`~/PYTHON/farfalle$ docker compose version`
`Docker Compose version v2.24.7`

im using :
`Operating System: Debian GNU/Linux 12 (bookworm)`
`Kernel: Linux 6.1.0-18-amd64`

**Comment by Stargate256** [comment]
Try installing newer docker: https://docs.docker.com/engine/install/debian/

That fixed this for me on debian.

**Comment by Dragonflysg** [comment]
hey thanks for the reply. i looked at it, but i have lots of docker apps running right now on this machine. the instruction says it will remove the old version before it can install a new one. so i can't do that right now .  i will try on another machine then. but thanks for the quick reply. much appreciated.
