### ISSUE TITLE
500: 1 validation error for RelatedQueries questions List should have at least 3 items after validation

### ISSUE THREAD

**Issue by gizbo** [rashadphz/farfalle#45]
This a new one: 
500: 1 validation error for RelatedQueries questions List should have at least 3 items after validation, not 1 [type=too_short, input_value=['What are the names of the affected cities?'], input_type=list] For further information visit https://errors.pydantic.dev/2.7/v/too_short

I'm not getting this consistenly, not sure what triggers that.   
Using Azure Open AI as provider

![image](https://github.com/rashadphz/farfalle/assets/493441/1e1f3e79-1103-4414-a23b-21174a46b773)

Thanks Yves

**Comment by gizbo** [comment]
What could cause the related query to only return 1 question back, not the expected 3?  And this is not happening all the time...  For now I changed the RelatedQueries model validation to be more permissive.

**Comment by gizbo** [comment]
Problem was with my deployment model... I think :)

**Comment by matsymbols** [comment]
I'm running to this error constantly while using gemma on ollama, any ideas where to fix the json response?
