### ISSUE TITLE
Error when using docker-compose

### ISSUE THREAD

**Issue by b3nis** [rashadphz/farfalle#49]
`ERROR: Invalid interpolation format for "backend" option in service "services": "OLLAMA_HOST=${OLLAMA_HOST:-http://localhost:11434}"`
`
ERROR: Invalid interpolation format for "backend" option in service "services": "ENABLE_LOCAL_MODELS=${ENABLE_LOCAL_MODELS:-True}"`

Getting these error when trying your docker-compose.dev.yml file. 

Anything I have done wrong?

**Comment by rashadphz** [comment]
The docker-compose file has been updated and there is now a .env-template. I've updated the README instructions. Let me know if you are still having issues.
