### ISSUE TITLE
A little reminder about copyright and unfair cloning of services

### ISSUE THREAD

**Issue by SeranaX** [rashadphz/farfalle#5]
Greetings.
Could you please change the design of the service a bit? Your current design "slightly" copies the design and features of the existing service "[Perplexity.AI](https://www.perplexity.ai)". 
Your OpenSource version is really good, but simply cloning an existing commercial product looks at least unfair to Perplexity developers.

Comparison of your service and Perplexity AI:
Your service             |  Perplexity AI
:-------------------------:|:-------------------------:
![Screenshot_2024-05-20-12-15-49-126_com android chrome~01](https://github.com/rashadphz/farfalle/assets/126817544/5bbaa207-487f-4c3a-8346-a2a973173d7e)  |  ![Screenshot_2024-05-20-12-16-01-051_com android chrome~01](https://github.com/rashadphz/farfalle/assets/126817544/15c95748-570d-41c7-9d2a-e14a84eb76ca)
![Screenshot_2024-05-20-12-15-55-994_com android chrome~01](https://github.com/rashadphz/farfalle/assets/126817544/c60e9707-d327-49c0-b858-140cfd8b282a)  |  ![Screenshot_2024-05-20-12-16-08-498_com android chrome~01](https://github.com/rashadphz/farfalle/assets/126817544/7838b3f0-6f64-4051-a760-d35232cafbe0)

**Comment by rashadphz** [comment]
Hey Serena, thanks for the feedback. The project is intended to be a clone of Perplexity.  I’m not commercializing the product at all or looking to compete with Perplexity. My intention is for people to see how Perplexity might be built, and provide a self-hosted alternative. 

I’ll consider a redesign, but for now I updated the README to make this more clear.

**Comment by arsaboo** [comment]
Also, showing information with images and other links has been used by other search engines even before Perplexity.
