### ISSUE TITLE
Does this open-source project currently provide an API？

### ISSUE THREAD

**Issue by liweibinggithub** [rashadphz/farfalle#53]
Does this open-source project currently provide an API

**Comment by quantumalchemy** [comment]
looks like there is an endpoint at :3000
but no info .. just installed I will look into this today 
maybe same params as the searxng api ?  - anyone know ??

**Comment by liweibinggithub** [comment]
There is no information about the API found on the official website or code documentation. If the API is not open, it may not be very mature.

**Comment by rashadphz** [comment]
If you self-host it, you can access the API at https://localhost:8000/. 

The only endpoint is `/chat`, this is what the request should look like:

```
{
  "thread_id": null,
  "query": "Your question here",
  "history": [
    {
      "content": "Previous message",
      "role": "user"
    }
  ],
  "model": "gpt-3.5-turbo",
}
```

There are currently no plans to support an official API.

**Comment by duplaja** [comment]
Came across this as well. I know it's closed as not planned, but would love to see something like it in the future. This is one of the things I currently use Perplexity API for, and would love to be able to use this instead.
