### ISSUE TITLE
how to solve 500: Missing keys: ['OLLAMA_API_BASE']

### ISSUE THREAD

**Issue by FemBoxbrawl** [rashadphz/farfalle#54]
![Screenshot 2024-06-19 144631](https://github.com/rashadphz/farfalle/assets/129459206/099d70ec-4c58-47d9-a04a-f4b28c9beb2d)

i am not a coder so i have no idea what to do

**Comment by FemBoxbrawl** [comment]
what do I have to do to make this work...

**Comment by arsaboo** [comment]
Please read the docs carefully....and add the relevant configuration option.

**Comment by FemBoxbrawl** [comment]
i forgot to mention i already had ollama running while this was happening

**Comment by rashthedude** [comment]
I'm having the same issue. The documentations aren't extremely clear on this matter. Can someone help or elaborate?

**Comment by Schmoaaaaah** [comment]
you should already have a enviorment variable OLLAMA_HOST
just add another one with OLLAMA_API_BASE and the same content like OLLAMA_HOST
- OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}

**Comment by rashadphz** [comment]
This is my mistake, thanks for pointing it out! I just updated the docker files, this should be fixed.
