### ISSUE TITLE
How do I change the OpenAI base url?

### ISSUE THREAD

**Issue by hubbdavid** [rashadphz/farfalle#57]
How do I change the OpenAI base url?

**Comment by anzestrela** [comment]
I have had some success by modifying the line 43 of "src/backend/llm/base.py" to: ```self.llm = LiteLLM(model=model, api_base="http://192.168.73.78:5000/v1")``` where "http://192.168.73.78:5000/v1"  is the IP of your server.

Doing this, it will generate a response and then error saying that the API key is invalid.

I inform you if I manage to fix this.
