### ISSUE TITLE
Running on a remote server the 'chat' calls go to localhost:8000

### ISSUE THREAD

**Issue by JayCroghan** [rashadphz/farfalle#61]
When viewing Network in Developer Tools the calls all timeout because they are going to localhost even though it's on a remote server.

<img width="1807" alt="image" src="https://github.com/rashadphz/farfalle/assets/1171148/a1bd326d-a903-4439-a55c-0663a1b399c6">

**Comment by rashadphz** [comment]
You can change this by setting `NEXT_PUBLIC_API_URL` in your .env. 
All of the adjustable variables are in the docker-compose file.
