### ISSUE TITLE
NEXT_PUBLIC_API_URL ignores specified port

### ISSUE THREAD

**Issue by AxelFooley** [rashadphz/farfalle#65]
I have just deployed Farfalle using docker compose, i have other containers running on this host and for this reason i changed my variable with the host IP and port 8003.

When i submit a search though i see that the requests to /chat are being sent to the right IP but on the wrong port (8000) where it's running another service that is of course refusing them.
![image](https://github.com/rashadphz/farfalle/assets/5037273/4d913815-62ed-4a28-aa2a-2ed1258a76d2)
![image](https://github.com/rashadphz/farfalle/assets/5037273/96d03575-6fba-4e65-ab8a-7072d729f4bd)

**Comment by rashadphz** [comment]
Can you try running `docker-compose -f docker-compose.dev.yaml up -d --build`?
This should rebuild the frontend image with your new port. Let me know if this works.

**Comment by AxelFooley** [comment]
Dude, i am surprised by how fast you replied. Thanks!

Your suggestion indeed solves the problem, i do see a new message in the logs but it just a warning and apparently everything is working as expected, but FYI:

searxng-1   | 2024-06-30 21:03:37,718 WARNING:searx.engines.openverse: ErrorContext('searx/search/processors/online.py', 125, 'count_error(', None, '1 redirects, maximum: 0', ('200', 'OK', 'api.openverse.org')) True

**Comment by rashadphz** [comment]
No problem :) 

You can ignore those logs, they shouldn't cause any problems. Let me know if there is anything else!
