### ISSUE TITLE
Remember model settings

### ISSUE THREAD

**Issue by arsaboo** [rashadphz/farfalle#7]
Every time I go to the home screen, the Local flag resets to Off (even when I have `ENABLE_LOCAL_MODELS=True` in the .env). Is there a way to retain the flag setting until the user toggles it?

**Comment by rashadphz** [comment]
There isn't currently, but it shouldn't take too long to implement. I'll work on that now.

**Comment by rashadphz** [comment]
Just pushed the change, feel free to re-open if there are any problems
