### ISSUE TITLE
bug report: multi-language support. Could not responese in chinese and japanese 

### ISSUE THREAD

**Issue by getofferhelp** [rashadphz/farfalle#9]
when I testing in Chinese and Japanese, it just reply in English.

Korean, french and germeny is ok, it would reply in same language to the input.
Example:

English:

Are cats and lions closely related?

Korean:

고양이와 사자, 친척인가요?

French:

Les chats et les lions sont-ils des parents proches ?

Germeny:

Sind Katzen und Löwen nahe Verwandte?

Chinese: 

猫和狮子是近亲吗

Japanese:

猫とライオンは近縁ですか。

**Comment by getofferhelp** [comment]
I translated  the prompt to Chinese version and reploy, but the result is the same  T T

**Comment by rashadphz** [comment]
Fixed in: https://github.com/rashadphz/farfalle/pull/12

**Comment by getofferhelp** [comment]
> Fixed in: #12

Cool and thank you so much!

**Comment by getofferhelp** [comment]
> Fixed in: #12
<img width="663" alt="屏幕截图 2024-05-21 100343" src="https://github.com/rashadphz/farfalle/assets/13744916/4baccde9-5fec-41fb-9581-6386a1f0bcbb">
when select the question related, follow up answer is still English.

(the Chinese text in 2 red circles means: why the flame is blue.
